### ISSUE TITLE
torch.utils.ffi is deprecated

### ISSUE THREAD

**Issue by ghost** [simonm3/maskr#1]
Hi there,

thank you for the good structured repo here.
Unfortunately I am getting this error (relatively new to python):
Compiling crop_and_resize kernels by nvcc...
./make.sh: line 12: nvcc: command not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/Users/********/opt/anaconda3/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Compiling nms kernels by nvcc...
./make.sh: line 20: nvcc: command not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/Users/********/opt/anaconda3/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")

What can I da about it?

Downgrading to torch 1.0 does not help (as intended in another issue). Also I dont want to downgrade to 0.4 since the version is too old.
Also I dont know how to change it to torch.utils.cpp_extension.

Regards

**Comment by simonm3** [comment]
You need nvcc installed as this compiles stuff for cuda. it is part of
cudatoolkit.

The other issue I am not sure. However the code was working with pytorch
1.0. You might try finding old source code for torch.utils.ffi and putting
it in your python path. I remember having the error and doing something
like that to fix it. I think you only need it to compile the c code.
Alternatively find a cpp version of nms and cropresize. At the time nobody
had done that though.

**Comment by ghost** [comment]
Hi Simon,

thank you for the answer, I will try this although I am looking into facebooks implementation detectron2 right now.

> Am 10.12.2019 um 19:05 schrieb simon <notifications@github.com>:
> 
> You need nvcc installed as this compiles stuff for cuda. it is part of
> cudatoolkit.
> 
> The other issue I am not sure. However the code was working with pytorch
> 1.0. You might try finding old source code for torch.utils.ffi and putting
> it in your python path. I remember having the error and doing something
> like that to fix it. I think you only need it to compile the c code.
> Alternatively find a cpp version of nms and cropresize. At the time nobody
> had done that though.
> 
> 
> 
> 
>

**Comment by ghost** [comment]
I actually like fastai more than fb's stuff but am undecided since they are really good supported. But fastai has the 1-cycle super convergence training etc. and your implementation is just more straight forward than fbs with lots of variables and yaml files...

**Comment by ghost** [comment]
its also part of torchvision now 
(https://github.com/pytorch/vision/blob/master/torchvision/ops/boxes.py)
